### ISSUE TITLE
Add py3 packages for scipy/matplot/etc

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs-docker-images#1]
We have the py2 packages, use the py3 packages if we have them.

**Comment by cdeil** [comment]
:+1: , thanks!

I have a package for which I can't use readthedocs because it's Python 3 only and needs scipy and matplotlib:
https://github.com/rtfd/readthedocs.org/issues/1131#issuecomment-114837148

And I have [another package](https://github.com/gammapy/gammapy/pull/343) where I need [h5py](http://www.h5py.org/) ... if it's easy to do, could you please include that as well?

**Comment by agjohnson** [comment]
This should be resolved in master
